SpoutMenu:
     Key: M
name1: Towny Map
command1: /towny map
name2: Towny Big Map
command2: /towny map big
name3: Town Info
command3: /town
name4: Nation Info
command4: /nation
name5: Plot Claim
command5: /plot claim
name6: Set Shop
command6: /plot set shop
name7: Town Spawn
command7: /town spawn
name8: Town +1000
command8: /town deposit 1000
name9: Town -1000
command9: /town withdraw 1000
name10: Nation +1000
command10: /nation deposit 1000
name11: Nation -1000
command11: /nation withdraw 1000
name12: Town Claim
command12: /town claim
name13: Spawn
command13: /spawn
name14: Balance
command14: /balance
name15: Repair All
command15: /rep all
name16: Sell Cobblestone
command16: /sell cobblestone
name17: Sell Wood
command17: /sell wood
name18: Sell Log
command18: /sell log
name19: Sell Dirt
command19: /sell dirt
name20: Jobs Help
command20: /jobs
name21: LWC Help
command21: /lwc
