SpoutMenu:
  Key: M
name1: Towny Map
command1: /towny map big
name2: Town Spawn
command2: /town spawn
name3: Server Spawn
command3: /spawn
name4: Nation Info
command4: /nation
name5: Town Info
command5: /town
name6: Town Claim
command6: /town claim
name7: Plot Claim
command7: /plot claim
name8: Repair Hand
command8: /rep
name9: Repair All
command9: /rep all
name10: Worth
command10: /worth
name11: Buy Backpack
command11: /backpack buy
name12: Upgrade Backpack
command12: /backpack upgrade
name13: Job Stats
command13: /jobs stats
name14: Manhunter
command14: /jobs join manhunter
name15: Blacksmith
command15: /jobs join blacksmith
name16: Miner
command16: /jobs join miner
name17: Hunter
command17: /jobs join hunter
name18: Farmer
command18: /jobs join farmer
name19: MonsterHunter
command19: /jobs join monsterhunter
name20: Woodcutter
command20: /jobs join woodcutter
name21: Fisherman
command21: /jobs join fisherman
