name: SpoutMenu
version: 0.8
description: Menu System using SpoutAPI.
authors: [AVirusC]

main: me.avirusc.SpoutMenu.SpoutMenu

depend: [Spout]

permissions:
     spoutmenu.*:
          description: Gives access to all of SpoutMenu.
          children:
               spoutmenu.allow: true
               spoutmenu.menu2: true
               spoutmenu.menu3: true
               spoutmenu.menu4: true
               spoutmenu.menu5: true
               spoutmenu.menu6: true
               spoutmenu.menu7: true
               spoutmenu.menu8: true
               spoutmenu.menu9: true
               spoutmenu.menu10: true
     spoutmenu.allow:
          description: Allow users to access menu.
     spoutmenu.menu2:
          description: Allow users see and to access menu 2.
     spoutmenu.menu3:
          description: Allow users to see and to access menu 3.
     spoutmenu.menu4:
          description: Allow users to see and to access menu 4.
     spoutmenu.menu5:
          description: Allow users to see and to access menu 5.
     spoutmenu.menu6:
          description: Allow users to see and to access menu 6.
     spoutmenu.menu7:
          description: Allow users to see and to access menu 7.
     spoutmenu.menu8:
          description: Allow users to see and to access menu 8.
     spoutmenu.menu9:
          description: Allow users to see and to access menu 9.
     spoutmenu.menu10:
          description: Allow users to see and to access menu 10.